import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/common/Navigation/navigation";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className="mx-5">
        <header>
          <Navigation />
        </header>
        <main>{children}</main>
        <Toaster></Toaster>
        <footer className="flex justify-center items-center h-16">
          <p>&copy; Made By Prajjwal Singh with ❤️. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
